FROM openjdk:11-jre
ADD ./spp-example-webapp-1.0.zip /spp-example-webapp-1.0.zip

COPY ./apache-skywalking-apm-es7-8.1.0.tar.gz /apache-skywalking-apm-es7-8.1.0.tar.gz
RUN tar -xzf ./apache-skywalking-apm-es7-8.1.0.tar.gz

#ADD ./agent.config /apache-skywalking-apm-bin/agent/config/agent.config
#ADD ./customize_enhance.xml /apache-skywalking-apm-bin/agent/config/customize_enhance.xml

#ENV SOURCE_CONFIG=docker-core.json
ENV JAVA_OPTS="-javaagent:/apache-skywalking-apm-bin-es7/agent/skywalking-agent.jar"

RUN unzip *.zip
CMD ["./spp-example-webapp-1.0-SNAPSHOT/bin/spp-example-webapp"]